# Generated by Django 4.1.7 on 2023-03-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_bookappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='booking_time',
        ),
    ]
