# Generated by Django 4.1.7 on 2023-03-08 10:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_bookappointment_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
