# Generated by Django 4.1.7 on 2023-03-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_bookappointment_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Contact Us', 'Contact Us')], max_length=100, null=True),
        ),
    ]
