# Generated by Django 4.1.7 on 2023-03-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_bookappointment_note_bookappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], max_length=100, null=True),
        ),
    ]
